### ISSUE TITLE
Change foreground colors to best contrast

### ISSUE THREAD

**Issue by adrianog3** [getomni/insomnia#9]
I suggest change the foreground colors to improve contrast. The white color makes it difficult to see the status of the request.

`
foreground: {
	default: '#f8f8f2',
	success: '#282a36',
	notice: '#282a36',
	warning: '#282a36',
	danger: '#282a36',
	surprise: '#282a36',
	info: '#282a36'
}
`

Before:

![success-before](https://user-images.githubusercontent.com/21218657/112706334-edfe8700-8e79-11eb-94ff-cff9e8c91749.png)

After:

![success-after](https://user-images.githubusercontent.com/21218657/112706341-f3f46800-8e79-11eb-9d9e-4ad50a9f178d.png)

**Comment by jpedroschmitz** [comment]
Hey @adrianog3, thanks for the suggestion! It really makes sense 💜 

I'll be fixing this issue soon and releasing a new version!
